config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root to: "homes#top"
    get "search" => "searches#search"
    resources :customers,only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update] do
      resources :order_items, only: [:update]
    end
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
  end

  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about", as: "about"
    get "orders/complete" => "orders#complete"
    get "/customers/my_page" => "customers#show"
    get "/customers/unsubscribe" => "customers#unsubscribe"
    get "search" => "searches#search"
    post "orders/confirm" => "orders#confirm"
    patch "/customers/withdraw" => "customers#withdraw"
    delete "/cart_items/destroy_all" => "cart_items#destroy_all"
    resource :customers, only: [:edit, :update]
    resources :orders, only: [:new, :create, :index, :show]
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :addresses, only: [:index, :create, :destroy, :edit, :update]
  end

  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, controllers: {
    sessions: "public/sessions",
    passwords: "public/passwords",
    registrations: "public/registrations"
  }

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy

  attachment :image

  validates :genre_id, :name, :price, presence: true
  validates :caption, length: {maximum: 200}
  validates :price, numericality: { only_integer: true }

  def self.looks(search)
    return none if search.blank?
    if search
      Item.where(['name LIKE ?', "%#{search}%"])
    else
      Item.all
    end
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  before_action :authenticate_admin!
  before_action :set_items, only: [:new, :create, :edit, :update]

  def new
    @item = Item.new

  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render 'new'
    end
  end

  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render 'edit'
    end
  end

  def set_items
    @item = Item.all
  end

  private
  def item_params
    params.require(:item).permit(:name, :image, :caption,
       :genre_id, :price, :is_active)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/_form_item.html.erb
<div class="form-group">
  <%= f.label :"商品画像", class: "col-sm-2 control-label" %>
  <%= f.attachment_field :image, class: "image" %>
</div>
<div class="form-group">
  <%= f.label :"商品名", class: "col-sm-2 control-label" %>
  <%= f.text_field :name, class: "col-sm-4 form-control-static name" %>
</div>
<div class="form-group">
  <%= f.label :"商品説明", class: "col-sm-2 control-label" %>
  <%= f.text_area :caption, class: "col-sm-4 control-label caption" %>
</div>
<div class="form-group">
  <%= f.label :"ジャンル", class: "col-sm-2 control-label" %>
  <%= f.collection_select(:genre_id, Genre.all, :id, :name, prompt: "-- 選択してください --", class: "col-sm-8 genre_id") %>
</div>
<div class="form-group">
  <%= f.label :"税抜価格", class: "col-sm-2 control-label" %>
  <%= f.text_field :price, class: "col-sm-4 control-label explanation" %>円
</div>
<div class="form-group radio_button">
  <%= f.label :"販売ステータス", class: "col-sm-2 control-label" %>
  <%= f.radio_button :is_active, true %>
  <%= f.label :is_active, "販売中", value: :true %>
  <%= f.radio_button :is_active, false, class: "ml-3" %>
  <%= f.label :is_active, "販売停止中", value: :false %>
</div>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-10 px-sm-0 mx auto">
      <h2 class="font-weight-bold mt-5 mb-5"><i class="fas fa-edit"></i>商品編集</h3>
        <%= form_with model: [:admin, @item], local: true do |f| %>
          <%= render 'form_item', f: f %>
          <%= f.submit '変更を保存', class: "btn btn-success btn-md my-3 mx-5" %>
        <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-7 px-sm-0 mx-auto">
      <h2 class="font-weight-bold mt-5">商品一覧</h2>
    </div>
    <div class="col-sm-3 px-sm-0 mt-5 text-center">
      <%= link_to "新規登録", new_admin_item_path, class: "btn btn-success" %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-10 px-sm-0 mx-auto">
      <table class="table table-hover table-inverse mt-3 mb-5">
        <thead>
          <tr>
            <th class="table-light border-dark">商品ID</th>
            <th class="table-light border-dark">商品名</th>
            <th class="table-light border-dark">税抜価格</th>
            <th class="table-light border-dark">ジャンル</th>
            <th class="table-light border-dark">ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
          <tr>
            <td class="align-middle border-dark">
              <%= item.id %>
            </td>
            <td class="align-middle border-dark">
              <%= link_to admin_item_path(item.id), class: "text-dark" do %>
                <%= item.name %>
              <% end %>
            </td>
            <td class="align-middle border-dark">
              <%= item.price.to_s(:delimited) %>
            </td>
            <td class="align-middle border-dark">
              <%= item.genre.name %>
            </td>
            <td class="border-dark">
              <% if item.is_active == true %>
                <p class="text-success mt-3">販売中</p>
              <% else  %>
                <p class="text-danger mt-3">>販売停止中</p>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <%= paginate @items, class: "text-center" %>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-10 px-sm-0 mx-auto">
      <h2 class="font-weight-bold mt-5 mb-5"><i class="fas fa-plus-square"></i>商品新規登録</h2>
        <%= form_with model: [:admin, @item], url: admin_items_path, local:true do |f| %>
          <%= render 'form_item', f: f %>
          <%= f.submit "新規登録", class: "btn btn-success btn-md my-3 mx-5" %>
        <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row justify-content-center">
	  <div class="col-sm-5 px-sm-0">
	    <h2 class="font-weight-bold mt-5">商品詳細</h2>
	    <p class="image mb-5">
          <%= attachment_image_tag(@item, :image, width: "100%", fallback: "no_image.jpg") %>
      </p>
    </div>
    <div class="col-sm-5 offset-sm-1 px-sm-0">
      <div class="mt-5 pt-4">
        <div class="font-weight-bold">商品名</div>
          <p><%= @item.name %></p>
        <div class="font-weight-bold">商品説明</div>
          <p><%= @item.caption %></p>
        <div class="font-weight-bold">ジャンル</div>
          <p><%= @item.genre.name %></p>
        <div class="font-weight-bold">税込価格(税抜価格)</div>
          <p><%= ((@item.price*1.10).to_i).to_s(:delimited) %>&nbsp;（<%= (@item.price).to_s(:delimited) %>）円</p>
        <div class="font-weight-bold">販売ステータス</div>
          <% if @item.is_active == true %>
            <strong><span class="text-success">販売中</span></strong>
          <% else %>
            <strong><span class="text-muted">販売停止中</span></strong>
          <% end %>
      </div>
      <%= link_to "編集する", edit_admin_item_path(@item.id), class: "btn btn-success btn-md mt-2" %>
    </div>
  </div>
</div>