config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root to: "homes#top"
    get "search" => "searches#search"
    resources :customers,only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update] do
      resources :order_items, only: [:update]
    end
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
  end

  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about", as: "about"
    get "orders/complete" => "orders#complete"
    get "/customers/my_page" => "customers#show"
    get "/customers/unsubscribe" => "customers#unsubscribe"
    get "search" => "searches#search"
    post "orders/confirm" => "orders#confirm"
    patch "/customers/withdraw" => "customers#withdraw"
    delete "/cart_items/destroy_all" => "cart_items#destroy_all"
    resource :customers, only: [:edit, :update]
    resources :orders, only: [:new, :create, :index, :show]
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :addresses, only: [:index, :create, :destroy, :edit, :update]
  end

  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, controllers: {
    sessions: "public/sessions",
    passwords: "public/passwords",
    registrations: "public/registrations"
  }

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  VALID_PHONE_NUMBER_REGEX = /\A0(\d{1}[-(]?\d{4}|\d{2}[-(]?\d{3}|\d{3}[-(]?\d{2}|\d{4}[-(]?\d{1})[-)]?\d{4}\z|\A0[5789]0[-]?\d{4}[-]?\d{4}\z/
  KATAKANA_REGEXP = /\A[\p{katakana}\u{30fc}]+\z/

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, :first_name, :address, presence: true
  validates :kana_last_name, :kana_first_name, presence: true, format: { with: KATAKANA_REGEXP }
  validates :postal_code, presence: true, length: {is: 7}, numericality: { only_integer: true }
  validates :phone_number, presence: true, format: { with: VALID_PHONE_NUMBER_REGEX }

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

  def self.looks(search)
    return none if search.blank?
    if search
      Customer.where(['last_name || first_name || kana_last_name || kana_first_name LIKE ?', "%#{search}%"])
    else
      Customer.all
    end
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers=Customer.all.page(params[:page]).per(10)
  end

  def show
    @customer=Customer.find(params[:id])
  end

  def edit
    @customer=Customer.find(params[:id])
  end

  def update
    @customer=Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(params[:id])
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :kana_last_name, :kana_first_name, :postal_code, :address, :phone_number, :email, :is_deleted)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 px-sm-0 mb-3">
      <h2 class="font-weight-bold mt-5 mb-3 mx-3">
        <i class="fas fa-users-cog"></i><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集
      </h2>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-10 px-sm-0 mb-3">
      <%= form_with model: [:admin, @customer], local: true do |f| %>
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td style="width: 20%">会員ID</td>
            <td style="width: 20%"><%= @customer.id %></td>
          </tr>
          <tr>
            <td>氏名</td>
            <td><%= f.text_field :last_name %></td>
            <td><%= f.text_field :first_name %></td>
          </tr>
          <tr>
            <td>フリガナ</td>
            <td><%= f.text_field :kana_last_name %></td>
            <td><%= f.text_field :kana_first_name %></td>
          </tr>
          <tr>
            <td>郵便番号</td>
            <td><%= f.text_field :postal_code %></td>
          </tr>
          <tr>
            <td>住所</td>
            <td colspan="2"><%= f.text_field :address, class: "col-9" %></td>
          </tr>
          <tr>
            <td>電話番号</td>
            <td><%= f.text_field :phone_number %></td>
          </tr>
          <tr>
            <td>メールアドレス</td>
            <td><%= f.text_field :email %></td>
          </tr>
          <tr>
            <td>会員ステータス</td>
            <td>
              <%= f.radio_button :is_deleted, :false %>有効
              <%= f.radio_button :is_deleted, :true %>退会
            </td>
          </tr>
          <tr>
            <td colspan="1"></td>
            <td><%= f.submit "変更を保存" , class: "btn btn-success btn-md" %></td>
          </tr>
        </tbody>
      </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-10 px-sm-0 mx-auto">
      <h2 class="font-weight-bold mt-5"><i class="fas fa-users"></i>会員一覧</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-10 px-sm-0 mx-auto">
      <table class="table table-hover table-inverse mt-3 mb-5">
        <thead>
          <tr>
            <th class="table-light border-dark">会員ID</th>
            <th class="table-light border-dark">氏名</th>
            <th class="table-light border-dark">メールアドレス</th>
            <th class="table-light border-dark">ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
          <tr>
            <td class="align-middle border-dark"><%= customer.id %></td>
            <td class="align-middle border-dark">
              <%= link_to admin_customer_path(customer.id), class: "text-dark" do %>
                <%= customer.last_name %> <%= customer.first_name %>
              <% end %>
            </td>
            <td class="align-middle border-dark"><%= customer.email %></td>
            <td class="align-middle border-dark">
              <% if customer.is_deleted == true %>
                <p class="text-secondary mt-3">退会</p>
              <% else %>
                <p class="text-success mt-3">有効</p>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <%= paginate @customers, class: "text-center" %>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 my-5">
      <h2 class="mb-5 font-weight-bold"><i class="far fa-user"></i><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h2>
      <table class="table table-bordered">
        <tbody>
          <tr>
            <td class="border-dark table-light" style="width: 40%">会員ID</td>
            <td class="border-dark"><%= @customer.id %></td>
          </tr>
          <tr>
            <td class="border-dark table-light" style="width: 40%">氏名</td>
            <td class="border-dark"><%= @customer.last_name %>　<%= @customer.first_name %></td>
          </tr>
          <tr>
            <td class="border-dark table-light" style="width: 40%">フリガナ</td>
            <td class="border-dark"><%= @customer.kana_last_name %>　<%= @customer.kana_first_name %></td>
          </tr>
          <tr>
            <td class="border-dark table-light" style="width: 40%">郵便番号</td>
            <td class="border-dark"><%= @customer.postal_code %></td>
          </tr>
          <tr>
            <td class="border-dark table-light" style="width: 40%">住所</td>
            <td class="border-dark"><%= @customer.address %></td>
          </tr>
          <tr>
            <td class="border-dark table-light" style="width: 40%">電話番号</td>
            <td class="border-dark"><%= @customer.phone_number %></td>
          </tr>
          <tr>
            <td class="border-dark table-light" style="width: 40%">メールアドレス</td>
            <td class="border-dark"><%= @customer.email %></td>
          </tr>
          <tr>
            <td class="border-dark table-light" style="width: 40%">会員ステータス</td>
            <td class="border-dark">
              <% if @customer.is_deleted == false %>
                <p class="text-success">有効</p>
              <% else %>
                <p class="text-secondary">退会</p>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
      <%= link_to "編集する", edit_admin_customer_path(@customer.id), class: "btn btn-success mr-4 mt-3" %>
      <%= link_to "注文履歴一覧を見る", admin_root_path, class: "btn btn-primary mt-3" %>
    </div>
  </div>
</div>