config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root to: "homes#top"
    get "search" => "searches#search"
    resources :customers,only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update] do
      resources :order_items, only: [:update]
    end
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
  end

  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about", as: "about"
    get "orders/complete" => "orders#complete"
    get "/customers/my_page" => "customers#show"
    get "/customers/unsubscribe" => "customers#unsubscribe"
    get "search" => "searches#search"
    post "orders/confirm" => "orders#confirm"
    patch "/customers/withdraw" => "customers#withdraw"
    delete "/cart_items/destroy_all" => "cart_items#destroy_all"
    resource :customers, only: [:edit, :update]
    resources :orders, only: [:new, :create, :index, :show]
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :addresses, only: [:index, :create, :destroy, :edit, :update]
  end

  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, controllers: {
    sessions: "public/sessions",
    passwords: "public/passwords",
    registrations: "public/registrations"
  }

end

app/controllers/admin/searches_controller.rb
class Admin::SearchesController < ApplicationController
  def search
    @items = Item.looks(params[:search]).page(params[:page]).per(5)
    @customers = Customer.looks(params[:search]).page(params[:page]).per(5)
  end
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/views/admin/searches/search.html.erb
<!--会員検索一覧-->
<div class="container">
  <div class="row">
    <div class="col-sm-10 px-sm-0 mx-auto">
      <h2 class="font-weight-bold mt-5"><i class="fas fa-users"></i>会員一覧</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-10 px-sm-0 mx-auto">
      <table class="table table-hover table-inverse mt-3 mb-5">
        <thead>
          <tr>
            <th class="table-light border-dark">会員ID</th>
            <th class="table-light border-dark">氏名</th>
            <th class="table-light border-dark">メールアドレス</th>
            <th class="table-light border-dark">ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
          <tr>
            <td class="align-middle border-dark"><%= customer.id %></td>
            <td class="align-middle border-dark">
              <%= link_to admin_customer_path(customer.id), class: "text-dark" do %>
                <%= customer.last_name %> <%= customer.first_name %>
              <% end %>
            </td>
            <td class="align-middle border-dark"><%= customer.email %></td>
            <td class="align-middle border-dark">
              <% if customer.is_deleted == true %>
                <p class="text-secondary mt-3">退会</p>
              <% else %>
                <p class="text-success mt-3">有効</p>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <%= paginate @customers, class: "text-center" %>
</div>

<!--商品検索一覧-->
<div class="container">
  <div class="row">
    <div class="col-sm-7 px-sm-0 mx-auto">
      <h2 class="font-weight-bold mt-5"><i class="fas fa-search-plus"></i>商品一覧</h2>
    </div>
    <div class="col-sm-3 px-sm-0 mt-5 text-center">
      <%= link_to "新規登録", new_admin_item_path, class: "btn btn-success" %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-10 px-sm-0 mx-auto">
      <table class="table table-hover table-inverse mt-3 mb-5">
        <thead>
          <tr>
            <th class="table-light border-dark">商品ID</th>
            <th class="table-light border-dark">商品名</th>
            <th class="table-light border-dark">税抜価格</th>
            <th class="table-light border-dark">ジャンル</th>
            <th class="table-light border-dark">ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
          <tr>
            <td class="align-middle border-dark">
              <%= item.id %>
            </td>
            <td class="align-middle border-dark">
              <%= link_to admin_item_path(item.id), class: "text-dark" do %>
                <%= item.name %>
              <% end %>
            </td>
            <td class="align-middle border-dark">
              <%= item.price.to_s(:delimited) %>
            </td>
            <td class="align-middle border-dark">
              <%= item.genre.name %>
            </td>
            <td class="border-dark">
              <% if item.is_active == true %>
                <p class="text-success mt-3">販売中</p>
              <% else  %>
                <p class="text-danger mt-3">>販売停止中</p>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <%= paginate @items, class: "text-center" %>
</div>