config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root to: "homes#top"
    get "search" => "searches#search"
    resources :customers,only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update] do
      resources :order_items, only: [:update]
    end
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
  end

  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about", as: "about"
    get "orders/complete" => "orders#complete"
    get "/customers/my_page" => "customers#show"
    get "/customers/unsubscribe" => "customers#unsubscribe"
    get "search" => "searches#search"
    post "orders/confirm" => "orders#confirm"
    patch "/customers/withdraw" => "customers#withdraw"
    delete "/cart_items/destroy_all" => "cart_items#destroy_all"
    resource :customers, only: [:edit, :update]
    resources :orders, only: [:new, :create, :index, :show]
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :addresses, only: [:index, :create, :destroy, :edit, :update]
  end

  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, controllers: {
    sessions: "public/sessions",
    passwords: "public/passwords",
    registrations: "public/registrations"
  }

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :postal_code, presence: true, length: {is: 7}, numericality: { only_integer: true }
  validates :address, :name, presence: true

  def shipping_address
    self.postal_code + self.address + self.name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  validates :number, presence: true
  validates :number, numericality: { only_integer: true }


  def item_price_with_tax
    (item.price*1.10).round
  end

  def sum
    (item.price*1.10*number).round
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  VALID_PHONE_NUMBER_REGEX = /\A0(\d{1}[-(]?\d{4}|\d{2}[-(]?\d{3}|\d{3}[-(]?\d{2}|\d{4}[-(]?\d{1})[-)]?\d{4}\z|\A0[5789]0[-]?\d{4}[-]?\d{4}\z/
  KATAKANA_REGEXP = /\A[\p{katakana}\u{30fc}]+\z/

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, :first_name, :address, presence: true
  validates :kana_last_name, :kana_first_name, presence: true, format: { with: KATAKANA_REGEXP }
  validates :postal_code, presence: true, length: {is: 7}, numericality: { only_integer: true }
  validates :phone_number, presence: true, format: { with: VALID_PHONE_NUMBER_REGEX }

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

  def self.looks(search)
    return none if search.blank?
    if search
      Customer.where(['last_name || first_name || kana_last_name || kana_first_name LIKE ?', "%#{search}%"])
    else
      Customer.all
    end
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy

  attachment :image

  validates :genre_id, :name, :price, presence: true
  validates :caption, length: {maximum: 200}
  validates :price, numericality: { only_integer: true }

  def self.looks(search)
    return none if search.blank?
    if search
      Item.where(['name LIKE ?', "%#{search}%"])
    else
      Item.all
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items, dependent: :destroy

  enum payment_method: { クレジットカード: 0, 銀行振込: 1 }
  enum status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}

  validates :customer_id, :address, :name, :shipping_fee, :payment_amount, :payment_method, presence: true
  validates :postal_code, presence: true, length: {is: 7}, numericality: { only_integer: true }
  validates :shipping_fee, :payment_amount, numericality: { only_integer: true }

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: {製作不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3}

  def tax_price
    (self.price * 1.10).round
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre=Genre.new
    @genres=Genre.all
  end

  def create
    @genre=Genre.new(genre_params)
    @genres=Genre.all
    @genre.save
    render "index"
  end

  def edit
    @genre=Genre.find(params[:id])
  end

  def update
    @genre=Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render "edit"
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    path = Rails.application.routes.recognize_path(request.referer)

    if path[:controller] == "admin/customers" && path[:action] == "show"
      @orders = Order.where(customer_id: path[:id]).page(params[:page]).per(10).order("created_at DESC")
    else
      @orders = Order.page(params[:page]).per(10).order("created_at DESC")
    end
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  before_action :authenticate_admin!
  before_action :set_items, only: [:new, :create, :edit, :update]

  def new
    @item = Item.new

  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render 'new'
    end
  end

  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render 'edit'
    end
  end

  def set_items
    @item = Item.all
  end

  private
  def item_params
    params.require(:item).permit(:name, :image, :caption,
       :genre_id, :price, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    if resource.class.name == "Admin"
      admin_root_path
    else
      flash[:success] = "Welcome！Nagano CAKE！"
      root_path
    end
  end

  def after_sign_out_path_for(resource)
    if resource == :admin
      new_admin_session_path
    else
      flash[:success] = "ログアウトしました"
      root_path
    end
  end

  before_action :authenticate_admin!, if: :admin_url

  def admin_url
    request.fullpath.include?("/admin")
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :kana_last_name, :kana_first_name, :postal_code, :address, :phone_number, :is_deleted])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/_error.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= "#{obj.errors.count}件のエラーがあります。ご確認ください。" %></h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class-"row">
      <p class="text-center pt-4">©Day-developers</p>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="container">
    <nav class="navbar navbar-expand-xl">
      <%= link_to image_tag("logo1.png"), "/", data: {"turbolinks" => false} %>
      <button class="navbar-toggler mx-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="fas fa-bars"></span>
      </button>

      <nav class="mx-auto collapse navbar-collapse justify-content-end", id="navbarSupportedContent">
        <ul class="navbar-nav mx-auto">
          <% if customer_signed_in? %>
            <li  class="nav-text my-3 text-center">
              ようこそ、<%= current_customer.last_name %>さん！
            </li>
            <p class="nav-button btn btn-sm mx-2 my-auto">
              <%= link_to "マイページ", customers_my_page_path, class: "nav-link" %>
            </p>
            <p class="nav-button btn btn-sm mx-2 my-auto">
              <%= link_to "商品一覧", items_path, class: "nav-link" %>
            </p>
            <p class="nav-button btn btn-sm mx-2 my-auto">
              <%= link_to "カート", cart_items_path, class: "nav-link" %>
            </p>
            <p class="nav-button btn btn-sm mx-2 my-auto">
              <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "nav-link" %>
            </p>
            <div class="nav-item dropdown mt-2">
              <div class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                ジャンル検索
              </div>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <% Genre.all.each do |genre| %>
                <a class="dropdown-item">
                  <%= link_to genre.name, search_path('search[value]': genre.id, 'search[how]': "match") %>
                </a>
                <% end %>
              </div>
            </div>
            <% elsif admin_signed_in? %>
            <p class="nav-button btn btn-sm mx-2 my-auto">
              <%= link_to "商品一覧", admin_items_path, class: "nav-link" %>
            </p>
            <p class="nav-button btn btn-sm mx-2 my-auto">
              <%= link_to "会員一覧", admin_customers_path, class: "nav-link" %>
            </p>
            <p class="nav-button btn btn-sm mx-2 my-auto">
              <%= link_to "注文履歴一覧", admin_root_path, class: "nav-link" %>
            </p>
            <p class="nav-button btn btn-sm mx-2 my-auto">
              <%= link_to "ジャンル一覧", admin_genres_path, class: "nav-link" %>
            </p>
            <p class="nav-button btn btn-sm mx-2 my-auto">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link" %>
            </p>
            <%= form_with url: admin_search_path, local: true, method: :get do |f| %>
              <%= f.text_field :search, class: "form-control-sm mt-2", style: "width:100px;", placeholder: "Search" %>
              <%= f.submit "検索", class: "btn btn-success btn-sm" %>
            <% end %>
            </div>
          <% else %>
            <p class="nav-button btn btn-sm mx-2 my-auto">
              <%= link_to "About", about_path, class: "nav-link" %>
            </p>
            <p class="nav-button btn btn-sm mx-2 my-auto">
              <%= link_to "商品一覧", items_path, class: "nav-link" %>
            </p>
            <p class="nav-button btn btn-sm mx-2 my-auto">
              <%= link_to "新規登録", new_customer_registration_path, class: "nav-link" %>
            </p>
            <p class="nav-button btn btn-sm mx-2 my-auto">
              <%= link_to "ログイン", new_customer_session_path, class: "nav-link" %>
            </p>
            <div class="nav-item dropdown mt-2">
              <div class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                ジャンル検索
              </div>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <% Genre.all.each do |genre| %>
                <a class="dropdown-item">
                  <%= link_to genre.name, search_path('search[value]': genre.id, 'search[how]': "match") %>
                </a>
                <% end %>
              </div>
            </div>
          <% end %>
        </ul>
      </nav>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/d903263f9b.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="main">
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>